name: Amazon Tracker

on:
  schedule:
    # Corre todos os dias às 10:00 UTC (11:00 em Portugal) e às 18:00 UTC (19:00 em Portugal)
    - cron: '0 10,18 * * *'
  workflow_dispatch: # Permite continuar a executar manualmente no painel se quiseres

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py
